<?php

namespace PcbKingdee\Mappings;

class InventoryMapping
{
    /**
     * @var array
     */
    public static $mapping = [
        [
            'name' => 'id',
            'attribute' => 'FId',
            'field' => 'FId',
            'type' => 'string',
            'comment' => '单据内码',
        ],
        [
            'name' => 'material_id',
            'attribute' => 'FMaterialId',
            'field' => 'FMaterialId',
            'type' => 'int',
            'comment' => '物料',
        ],
        [
            'name' => 'material_number',
            'attribute' => 'FMaterialId.FNumber',
            'field' => 'FMaterialId.FNumber',
            'type' => 'string',
            'comment' => '物料',
        ],
        [
            'name' => 'material_name',
            'attribute' => 'FMaterialId.FName',
            'field' => 'FMaterialId.FName',
            'type' => 'string',
            'comment' => '物料',
        ],
        [
            'name' => 'material_spec',
            'attribute' => 'FMaterialId.FSpecification',
            'field' => 'FMaterialId.FSpecification',
            'type' => 'string',
            'comment' => '规格',
        ],
        [
            'name' => 'material_package',
            'attribute' => 'FMaterialId.F_ORA_Text',
            'field' => 'FMaterialId.F_ORA_Text',
            'type' => 'string',
            'comment' => '封装',
        ],
        [
            'name' => 'lot_id',
            'attribute' => 'FLot',
            'field' => 'FLot',
            'type' => 'int',
            'comment' => '批号',
        ],
        [
            'name' => 'lot_number',
            'attribute' => 'FLot.FNumber',
            'field' => 'FLot.FNumber',
            'type' => 'string',
            'comment' => '批号',
        ],
        [
            'name' => 'lot_name',
            'attribute' => 'FLot.FName',
            'field' => 'FLot.FName',
            'type' => 'string',
            'comment' => '批号',
        ],
        [
            'name' => 'base_unit_id',
            'attribute' => 'FBaseUnitId',
            'field' => 'FBaseUnitId',
            'type' => 'int',
            'comment' => '基本单位',
        ],
        [
            'name' => 'base_unit_number',
            'attribute' => 'FBaseUnitId.FNumber',
            'field' => 'FBaseUnitId.FNumber',
            'type' => 'string',
            'comment' => '基本单位',
        ],
        [
            'name' => 'base_unit_name',
            'attribute' => 'FBaseUnitId.FName',
            'field' => 'FBaseUnitId.FName',
            'type' => 'string',
            'comment' => '基本单位',
        ],
        [
            'name' => 'unit_id',
            'attribute' => 'FStockUnitId',
            'field' => 'FStockUnitId',
            'type' => 'int',
            'comment' => '主单位',
        ],
        [
            'name' => 'unit_number',
            'attribute' => 'FStockUnitId.FNumber',
            'field' => 'FStockUnitId.FNumber',
            'type' => 'string',
            'comment' => '主单位',
        ],
        [
            'name' => 'unit_name',
            'attribute' => 'FStockUnitId.FName',
            'field' => 'FStockUnitId.FName',
            'type' => 'string',
            'comment' => '主单位',
        ],
        [
            'name' => 'num',
            'attribute' => 'FMaterialId.FStoreURNum',
            'field' => 'FMaterialId.FStoreURNum',
            'type' => 'int',
            'comment' => '分子',
        ],
        [
            'name' => 'nom',
            'attribute' => 'FMaterialId.FStoreURNom',
            'field' => 'FMaterialId.FStoreURNom',
            'type' => 'int',
            'comment' => '分母',
        ],
        [
            'name' => 'base_qty',
            'attribute' => 'FBaseQty',
            'field' => 'FBaseQty',
            'type' => 'int',
            'comment' => '库存量（基本单位）',
        ],
        // [
        //     'name' => 'qty',
        //     'attribute' => 'FQty',
        //     'field' => 'FQty',
        //     'type' => 'int',
        //     'comment' => '库存量（主单位）',
        // ],
        [
            'name' => 'stock_id',
            'attribute' => 'FStockId',
            'field' => 'FStockId',
            'type' => 'int',
            'comment' => '仓库',
        ],
        [
            'name' => 'stock_number',
            'attribute' => 'FStockId.FNumber',
            'field' => 'FStockId.FNumber',
            'type' => 'string',
            'comment' => '仓库',
        ],
        [
            'name' => 'stock_name',
            'attribute' => 'FStockId.FName',
            'field' => 'FStockId.FName',
            'type' => 'string',
            'comment' => '仓库',
        ],
        [
            'name' => 'stock_loc_id',
            'attribute' => 'FStockLocId',
            'field' => 'FStockLocId',
            'type' => 'int',
            'comment' => '仓位',
        ],
        [
            'name' => 'stock_loc_f100001',
            'attribute' => 'FStockLocId.FF100001',
            'field' => 'FStockLocId.FF100001',
            'type' => 'int',
            'comment' => '仓位',
        ],
        [
            'name' => 'stock_loc_f100001_number',
            'attribute' => 'FStockLocId.FF100001.FNumber',
            'field' => 'FStockLocId.FF100001.FNumber',
            'type' => 'string',
            'comment' => '仓位',
        ],
        [
            'name' => 'stock_loc_f100001_name',
            'attribute' => 'FStockLocId.FF100001.FName',
            'field' => 'FStockLocId.FF100001.FName',
            'type' => 'string',
            'comment' => '仓位',
        ],
        [
            'name' => 'stock_loc_f100002',
            'attribute' => 'FStockLocId.FF100002',
            'field' => 'FStockLocId.FF100002',
            'type' => 'int',
            'comment' => '仓位',
        ],
        [
            'name' => 'stock_loc_f100002_number',
            'attribute' => 'FStockLocId.FF100002.FNumber',
            'field' => 'FStockLocId.FF100002.FNumber',
            'type' => 'string',
            'comment' => '仓位',
        ],
        [
            'name' => 'stock_loc_f100002_name',
            'attribute' => 'FStockLocId.FF100002.FName',
            'field' => 'FStockLocId.FF100002.FName',
            'type' => 'string',
            'comment' => '仓位',
        ],
        [
            'name' => 'stock_org_id',
            'attribute' => 'FStockOrgId',
            'field' => 'FStockOrgId',
            'type' => 'int',
            'comment' => '库存组织',
        ],
        [
            'name' => 'stock_org_number',
            'attribute' => 'FStockOrgId.FNumber',
            'field' => 'FStockOrgId.FNumber',
            'type' => 'string',
            'comment' => '库存组织',
        ],
        [
            'name' => 'stock_org_name',
            'attribute' => 'FStockOrgId.FName',
            'field' => 'FStockOrgId.FName',
            'type' => 'string',
            'comment' => '库存组织',
        ],
        [
            'name' => 'owner_type_id',
            'attribute' => 'FOwnerTypeId',
            'field' => 'FOwnerTypeId',
            'type' => 'string',
            'comment' => '货主类型',
        ],
        [
            'name' => 'owner_id',
            'attribute' => 'FOwnerId',
            'field' => 'FOwnerId',
            'type' => 'int',
            'comment' => '货主',
        ],
        [
            'name' => 'owner_number',
            'attribute' => 'FOwnerId.FNumber',
            'field' => 'FOwnerId.FNumber',
            'type' => 'string',
            'comment' => '货主',
        ],
        [
            'name' => 'owner_name',
            'attribute' => 'FOwnerId.FName',
            'field' => 'FOwnerId.FName',
            'type' => 'string',
            'comment' => '货主',
        ],
        [
            'name' => 'keeper_type_id',
            'attribute' => 'FKeeperTypeId',
            'field' => 'FKeeperTypeId',
            'type' => 'string',
            'comment' => '保管者类型',
        ],
        [
            'name' => 'keeper_id',
            'attribute' => 'FKeeperId',
            'field' => 'FKeeperId',
            'type' => 'int',
            'comment' => '保管者',
        ],
        [
            'name' => 'keeper_number',
            'attribute' => 'FKeeperId.FNumber',
            'field' => 'FKeeperId.FNumber',
            'type' => 'string',
            'comment' => '保管者',
        ],
        [
            'name' => 'keeper_name',
            'attribute' => 'FKeeperId.FName',
            'field' => 'FKeeperId.FName',
            'type' => 'string',
            'comment' => '保管者',
        ],
    ];
}
