<?php

namespace PcbKingdee\Mappings\MfgOrder;

class EntryMapping
{
    /**
     * @var array
     */
    public static $mapping = [
        [
            'name' => 'entry_id',
            'attribute' => 'FTreeEntity_FEntryId',
            'field' => 'FEntryId',
            'type' => 'int',
            'comment' => '分录内码',
        ],
        [
            'name' => 'seq',
            'attribute' => 'FTreeEntity_FSeq',
            'field' => 'FSeq',
            'type' => 'int',
            'comment' => '行号',
        ],
        [
            'name' => 'material_id',
            'attribute' => 'FMaterialId',
            'field' => 'FMaterialId',
            'type' => 'int',
            'comment' => '物料',
        ],
        [
            'name' => 'material_number',
            'attribute' => 'FMaterialId.FNumber',
            'field' => 'FMaterialId.FNumber',
            'type' => 'string',
            'comment' => '物料',
        ],
        [
            'name' => 'material_name',
            'attribute' => 'FMaterialId.FName',
            'field' => 'FMaterialId.FName',
            'type' => 'string',
            'comment' => '物料',
        ],
        [
            'name' => 'material_spec',
            'attribute' => 'FMaterialId.FSpecification',
            'field' => 'FMaterialId.FSpecification',
            'type' => 'string',
            'comment' => '规格',
        ],
        [
            'name' => 'unit_id',
            'attribute' => 'FUnitId',
            'field' => 'FUnitId',
            'type' => 'int',
            'comment' => '单位',
        ],
        [
            'name' => 'unit_number',
            'attribute' => 'FUnitId.FNumber',
            'field' => 'FUnitId.FNumber',
            'type' => 'string',
            'comment' => '单位',
        ],
        [
            'name' => 'unit_name',
            'attribute' => 'FUnitId.FName',
            'field' => 'FUnitId.FName',
            'type' => 'string',
            'comment' => '单位',
        ],
        [
            'name' => 'qty',
            'attribute' => 'FQty',
            'field' => 'FQty',
            'type' => 'int',
            'comment' => '数量',
        ],
        [
            'name' => 'bom_id',
            'attribute' => 'FBomId',
            'field' => 'FBomId',
            'type' => 'int',
            'comment' => 'BOM版本',
        ],
        [
            'name' => 'bom_number',
            'attribute' => 'FBomId.FNumber',
            'field' => 'FBomId.FNumber',
            'type' => 'string',
            'comment' => 'BOM版本',
        ],
        [
            'name' => 'bom_name',
            'attribute' => 'FBomId.FName',
            'field' => 'FBomId.FName',
            'type' => 'string',
            'comment' => 'BOM版本',
        ],
        [
            'name' => 'status',
            'attribute' => 'FStatus',
            'field' => 'FStatus',
            'type' => 'string',
            'comment' => '业务状态',
        ],
        [
            'name' => 'sales_order_number',
            'attribute' => 'FSaleOrderNo',
            'field' => 'FSaleOrderNo',
            'type' => 'string',
            'comment' => '需求单据',
        ],
        [
            'name' => 'sales_order_seq',
            'attribute' => 'FSaleOrderEntrySeq',
            'field' => 'FSaleOrderEntrySeq',
            'type' => 'int',
            'comment' => '需求单据行号',
        ],
        [
            'name' => 'schedule_status',
            'attribute' => 'FScheduleStatus',
            'field' => 'FScheduleStatus',
            'type' => 'string',
            'comment' => '排产状态',
        ],
        [
            'name' => 'pick_mtrl_status',
            'attribute' => 'FPickMtrlStatus',
            'field' => 'FPickMtrlStatus',
            'type' => 'string',
            'comment' => '领料状态',
        ],
        [
            'name' => 'sourcing_options',
            'attribute' => 'F_ORA_Combo',
            'field' => 'F_ORA_Combo',
            'type' => 'string',
            'comment' => '供料方式',
        ],
        [
            'name' => 'ready_status',
            'attribute' => 'FBillStatus1',
            'field' => 'FBillStatus1',
            'type' => 'string',
            'comment' => '符合投产状态',
        ],
        [
            'name' => 'kitting_status',
            'attribute' => 'FBillStatus3',
            'field' => 'FBillStatus3',
            'type' => 'string',
            'comment' => '物料齐套状态',
        ],
        [
            'name' => 'kitting_remark',
            'attribute' => 'F_ORA_Remarks',
            'field' => 'F_ORA_Remarks',
            'type' => 'string',
            'comment' => '物料齐套备注',
        ],
        [
            'name' => 'smt_start_qty',
            'attribute' => 'F_ORA_Qty',
            'field' => 'F_ORA_Qty',
            'type' => 'int',
            'comment' => 'SMT开工数量',
        ],
        [
            'name' => 'smt_test_qty',
            'attribute' => 'F_ORA_Qty1',
            'field' => 'F_ORA_Qty1',
            'type' => 'int',
            'comment' => 'SMT检测数量',
        ],
        [
            'name' => 'smt_end_qty',
            'attribute' => 'F_ORA_Qty2',
            'field' => 'F_ORA_Qty2',
            'type' => 'int',
            'comment' => 'SMT结束数量',
        ],
        [
            'name' => 'dip_start_qty',
            'attribute' => 'F_ORA_Qty3',
            'field' => 'F_ORA_Qty3',
            'type' => 'int',
            'comment' => 'DIP开工数量',
        ],
        [
            'name' => 'pkg_start_qty',
            'attribute' => 'F_ORA_Qty4',
            'field' => 'F_ORA_Qty4',
            'type' => 'int',
            'comment' => '包装接收数量',
        ],
        [
            'name' => 'defect_qty',
            'attribute' => 'F_ORA_Qty5',
            'field' => 'F_ORA_Qty5',
            'type' => 'int',
            'comment' => '不良数量',
        ],
        [
            'name' => 'fail_qty',
            'attribute' => 'F_ORA_Qty6',
            'field' => 'F_ORA_Qty6',
            'type' => 'int',
            'comment' => '报废数量',
        ],
        [
            'name' => 'ready_date',
            'attribute' => 'F_ORA_Datetime',
            'field' => 'F_ORA_Datetime',
            'type' => 'string',
            'comment' => '符合投产时间',
        ],
        [
            'name' => 'smt_count',
            'attribute' => 'F_ORA_BaseProperty2',
            'field' => 'F_ORA_BaseProperty2',
            'type' => 'int',
            'comment' => 'SMT焊点数',
        ],
        [
            'name' => 'dip_count',
            'attribute' => 'F_ORA_BaseProperty3',
            'field' => 'F_ORA_BaseProperty3',
            'type' => 'int',
            'comment' => 'DIP焊点数',
        ],
        [
            'name' => 'smt_start_date',
            'attribute' => 'F_ORA_Datetime2',
            'field' => 'F_ORA_Datetime2',
            'type' => 'string',
            'comment' => 'SMT开工时间',
        ],
        [
            'name' => 'smt_test_date',
            'attribute' => 'F_ORA_Datetime3',
            'field' => 'F_ORA_Datetime3',
            'type' => 'string',
            'comment' => 'SMT检测时间',
        ],
        [
            'name' => 'smt_end_date',
            'attribute' => 'F_ORA_Datetime6',
            'field' => 'F_ORA_Datetime6',
            'type' => 'string',
            'comment' => 'SMT结束时间',
        ],
        [
            'name' => 'dip_start_date',
            'attribute' => 'F_ORA_Datetime1',
            'field' => 'F_ORA_Datetime1',
            'type' => 'string',
            'comment' => 'DIP开工时间',
        ],
        [
            'name' => 'pkg_start_date',
            'attribute' => 'F_ORA_Datetime4',
            'field' => 'F_ORA_Datetime4',
            'type' => 'string',
            'comment' => '包装接收时间',
        ],
        [
            'name' => 'delivery_date',
            'attribute' => 'F_ORA_Datetime5',
            'field' => 'F_ORA_Datetime5',
            'type' => 'string',
            'comment' => '要货日期',
        ],
    ];
}
