<?php

namespace PcbKingdee\Mappings\SalesOrder;

class MasterMapping
{
    /**
     * @var array
     */
    public static $mapping = [
        [
            'name' => 'id',
            'attribute' => 'FId',
            'field' => 'FId',
            'type' => 'int',
            'comment' => '单据内码',
        ],
        [
            'name' => 'bill_number',
            'attribute' => 'FBillNo',
            'field' => 'FBillNo',
            'type' => 'string',
            'comment' => '单据编号',
        ],
        [
            'name' => 'bill_type_id',
            'attribute' => 'FBillTypeId',
            'field' => 'FBillTypeId',
            'type' => 'string',
            'comment' => '单据类型',
        ],
        [
            'name' => 'bill_type_number',
            'attribute' => 'FBillTypeId.FNumber',
            'field' => 'FBillTypeId.FNumber',
            'type' => 'string',
            'comment' => '单据类型',
        ],
        [
            'name' => 'bill_type_name',
            'attribute' => 'FBillTypeId.FName',
            'field' => 'FBillTypeId.FName',
            'type' => 'string',
            'comment' => '单据类型',
        ],
        [
            'name' => 'date',
            'attribute' => 'FDate',
            'field' => 'FDate',
            'type' => 'string',
            'comment' => '日期',
        ],
        [
            'name' => 'document_status',
            'attribute' => 'FDocumentStatus',
            'field' => 'FDocumentStatus',
            'type' => 'string',
            'comment' => '单据状态',
        ],
        [
            'name' => 'sales_org_id',
            'attribute' => 'FSaleOrgId',
            'field' => 'FSaleOrgId',
            'type' => 'int',
            'comment' => '销售组织',
        ],
        [
            'name' => 'sales_org_number',
            'attribute' => 'FSaleOrgId.FNumber',
            'field' => 'FSaleOrgId.FNumber',
            'type' => 'string',
            'comment' => '销售组织',
        ],
        [
            'name' => 'sales_org_name',
            'attribute' => 'FSaleOrgId.FName',
            'field' => 'FSaleOrgId.FName',
            'type' => 'string',
            'comment' => '销售组织',
        ],
        [
            'name' => 'customer_id',
            'attribute' => 'FCustId',
            'field' => 'FCustId',
            'type' => 'int',
            'comment' => '客户',
        ],
        [
            'name' => 'customer_number',
            'attribute' => 'FCustId.FNumber',
            'field' => 'FCustId.FNumber',
            'type' => 'string',
            'comment' => '客户',
        ],
        [
            'name' => 'customer_name',
            'attribute' => 'FCustId.FName',
            'field' => 'FCustId.FName',
            'type' => 'string',
            'comment' => '客户',
        ],
        [
            'name' => 'receive_id',
            'attribute' => 'FReceiveId',
            'field' => 'FReceiveId',
            'type' => 'int',
            'comment' => '收货方',
        ],
        [
            'name' => 'receive_number',
            'attribute' => 'FReceiveId.FNumber',
            'field' => 'FReceiveId.FNumber',
            'type' => 'string',
            'comment' => '收货方',
        ],
        [
            'name' => 'receive_name',
            'attribute' => 'FReceiveId.FName',
            'field' => 'FReceiveId.FName',
            'type' => 'string',
            'comment' => '收货方',
        ],
        [
            'name' => 'head_loc_id',
            'attribute' => 'FHeadLocId',
            'field' => 'FHeadLocId',
            'type' => 'int',
            'comment' => '交货地点',
        ],
        [
            'name' => 'head_loc_number',
            'attribute' => 'FHeadLocId.FNumber',
            'field' => 'FHeadLocId.FNumber',
            'type' => 'string',
            'comment' => '交货地点',
        ],
        [
            'name' => 'head_loc_name',
            'attribute' => 'FHeadLocId.FName',
            'field' => 'FHeadLocId.FName',
            'type' => 'string',
            'comment' => '交货地点',
        ],
        [
            'name' => 'sales_man_id',
            'attribute' => 'FSalerId',
            'field' => 'FSalerId',
            'type' => 'int',
            'comment' => '销售员',
        ],
        [
            'name' => 'sales_man_number',
            'attribute' => 'FSalerId.FNumber',
            'field' => 'FSalerId.FNumber',
            'type' => 'string',
            'comment' => '销售员',
        ],
        [
            'name' => 'sales_man_name',
            'attribute' => 'FSalerId.FName',
            'field' => 'FSalerId.FName',
            'type' => 'string',
            'comment' => '销售员',
        ],
        [
            'name' => 'receive_address',
            'attribute' => 'FReceiveAddress',
            'field' => 'FReceiveAddress',
            'type' => 'string',
            'comment' => '收货方地址',
        ],
        [
            'name' => 'link_man',
            'attribute' => 'FLinkMan',
            'field' => 'FLinkMan',
            'type' => 'string',
            'comment' => '收货人姓名',
        ],
        [
            'name' => 'link_phone',
            'attribute' => 'FLinkPhone',
            'field' => 'FLinkPhone',
            'type' => 'string',
            'comment' => '收货人电话',
        ],
        [
            'name' => 'creator_id',
            'attribute' => 'FCreatorId',
            'field' => 'FCreatorId',
            'type' => 'string',
            'comment' => '创建人',
        ],
        [
            'name' => 'creator_name',
            'attribute' => 'FCreatorId.FName',
            'field' => 'FCreatorId.FName',
            'type' => 'string',
            'comment' => '创建人',
        ],
        [
            'name' => 'create_date',
            'attribute' => 'FCreateDate',
            'field' => 'FCreateDate',
            'type' => 'string',
            'comment' => '创建日期',
        ],
        [
            'name' => 'note',
            'attribute' => 'FNote',
            'field' => 'FNote',
            'type' => 'string',
            'comment' => '备注',
        ],
    ];
}
